[project]
name = "docs"
version = "0.1.0"
description = "Centralized documentation for projects created by Jonas Meyer-Ohle"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-material>=9.5.49",
    "mkdocs-multirepo-plugin>=0.8.3",
]
